# Generated by Django 2.0.1 on 2018-01-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180113_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.CharField(max_length=150),
        ),
    ]
