# Generated by Django 2.0.1 on 2018-01-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180114_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='headline',
            new_name='intro',
        ),
    ]
