# Generated by Django 2.0.1 on 2018-01-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20180114_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, default='https://x.kinja-static.com/assets/images/logos/placeholders/default.png', null=True),
        ),
    ]
