# Generated by Django 2.0.1 on 2018-01-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20180116_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, default='/static/images/img_default.png', null=True),
        ),
    ]
