# Generated by Django 2.0.1 on 2018-02-01 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20180201_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
